name: 'Amazon ECS "Render Task Definition" Action for GitHub Actions'
description: 'Inserts a container image URI into a container definition in an Amazon ECS task definition JSON file, creating a new file.'
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  task-definition:
    description: 'The path to the ECS task definition JSON file'
    required: true
  container-name:
    description: 'The name of the container defined in the containerDefinitions section of the ECS task definition'
    required: true
  image:
    description: 'The URI of the container image to insert into the ECS task definition'
    required: true
  secrets:
    description: 'Whether to incorporate secrets from parameter store or secrets manager using pre-defined secrets in the task definition or from an external file'
    required: false
  aws-region:
    description: 'AWS Region, e.g. us-east-2'
    required: false
  aws-account-id:
    description: 'AWS Account ID'
    required: false
outputs:
  task-definition:
    description: 'The path to the rendered task definition file'
runs:
  using: 'node12'
  main: 'dist/index.js'
